import React from "react";

const index = () => {
  return (
    <main className="main-section">
      <div className="table-content-wrapper">
        <h1 className="css-1uk1gs8">Major Limitations</h1>
        <p>
          We’ve known the major pros of using React, from its reusable
          components and high-performance capabilities to its easy-to-learn
          syntax and SEO friendliness. However, there are a few limitations
          associated with ReactJS which are:
        </p>
        <ul className="task-list">
          <li className="task-list-item">
            React is a library, not a framework. It is not a complete solution.
          </li>
          <li className="task-list-item">
            React is not SEO friendly. Technically it is possible to make it SEO
            friendly, but it is not easy. The reason is that React is a
            client-side rendering library. It means that the HTML is generated
            by JavaScript. So, the search engine bots cannot read the HTML. They
            can only read the HTML that is generated by the server.
          </li>
          <li className="task-list-item">
            React have no built-in routing system. It is not a problem if you
            are using React for small applications. But if you are using it for
            large applications, then you will need a routing system. You can use
            React Router for this purpose.
          </li>
          <li className="task-list-item">
            React have high inital load time. It is because React is a
            client-side rendering library. It means that the HTML is generated
            by JavaScript. So, the browser needs to download the JavaScript file
            first. Then it needs to execute the JavaScript file. Only after
            that, it can display the HTML on the screen.
          </li>
        </ul>
      </div>
    </main>
  );
};

export default index;
